
# Ключ проекта
sonar.projectKey=sbt_synd_01017356

# Расположение исходного кода
sonar.sources=.

# URL сервера SonarQube
sonar.host.url=https://portal.works.prod.sbt/ssd/tools/sonar

# Исключения для анализа
sonar.exclusions=**/*pb.go,*.groovy

# Язык проекта
sonar.language=go

# Путь к отчету о покрытии кода
sonar.go.coverage.reportPaths=cov.out