// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: synes/adapter/v1/ControlPlaneService.proto

package synes_adapter_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "portal.works.prod.sbt/ssd/tools/sc/synes/reactive-stream-adapter-api/grpc/io/cloudevents/v1"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_synes_adapter_v1_ControlPlaneService_proto protoreflect.FileDescriptor

const file_synes_adapter_v1_ControlPlaneService_proto_rawDesc = "" +
	"\n" +
	"*synes/adapter/v1/ControlPlaneService.proto\x12\x17ru.sbt.ss.event.adapter\x1a\"io/cloudevents/v1/CloudEvent.proto2i\n" +
	"\x13ControlPlaneService\x12R\n" +
	"\fStreamEvents\x12\x1d.io.cloudevents.v1.CloudEvent\x1a\x1d.io.cloudevents.v1.CloudEvent\"\x00(\x010\x01BR\n" +
	"\x0fru.sbt.ss.eventB\x16ControlPlaneServiceApiP\x01Z%api/synes_adapter/v1;synes_adapter_v1b\x06proto3"

var file_synes_adapter_v1_ControlPlaneService_proto_goTypes = []any{
	(*v1.CloudEvent)(nil), // 0: io.cloudevents.v1.CloudEvent
}
var file_synes_adapter_v1_ControlPlaneService_proto_depIdxs = []int32{
	0, // 0: ru.sbt.ss.event.adapter.ControlPlaneService.StreamEvents:input_type -> io.cloudevents.v1.CloudEvent
	0, // 1: ru.sbt.ss.event.adapter.ControlPlaneService.StreamEvents:output_type -> io.cloudevents.v1.CloudEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synes_adapter_v1_ControlPlaneService_proto_init() }
func file_synes_adapter_v1_ControlPlaneService_proto_init() {
	if File_synes_adapter_v1_ControlPlaneService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synes_adapter_v1_ControlPlaneService_proto_rawDesc), len(file_synes_adapter_v1_ControlPlaneService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synes_adapter_v1_ControlPlaneService_proto_goTypes,
		DependencyIndexes: file_synes_adapter_v1_ControlPlaneService_proto_depIdxs,
	}.Build()
	File_synes_adapter_v1_ControlPlaneService_proto = out.File
	file_synes_adapter_v1_ControlPlaneService_proto_goTypes = nil
	file_synes_adapter_v1_ControlPlaneService_proto_depIdxs = nil
}
