// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: synes/adapter/v1/EventAdapterService.proto

package synes_adapter_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "portal.works.prod.sbt/ssd/tools/sc/synes/reactive-stream-adapter-api/grpc/io/cloudevents/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED StatusCode = 0
	StatusCode_FAILED                  StatusCode = 1
	StatusCode_SUCCESS                 StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSPECIFIED",
		1: "FAILED",
		2: "SUCCESS",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSPECIFIED": 0,
		"FAILED":                  1,
		"SUCCESS":                 2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_synes_adapter_v1_EventAdapterService_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_synes_adapter_v1_EventAdapterService_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{0}
}

type PublishSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSettings) Reset() {
	*x = PublishSettings{}
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSettings) ProtoMessage() {}

func (x *PublishSettings) ProtoReflect() protoreflect.Message {
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSettings.ProtoReflect.Descriptor instead.
func (*PublishSettings) Descriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{0}
}

func (x *PublishSettings) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SubscribeSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSettings) Reset() {
	*x = SubscribeSettings{}
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSettings) ProtoMessage() {}

func (x *SubscribeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSettings.ProtoReflect.Descriptor instead.
func (*SubscribeSettings) Descriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeSettings) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CommitRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscribeSettings *SubscribeSettings     `protobuf:"bytes,1,opt,name=subscribeSettings,proto3" json:"subscribeSettings,omitempty"`
	Id                string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetSubscribeSettings() *SubscribeSettings {
	if x != nil {
		return x.SubscribeSettings
	}
	return nil
}

func (x *CommitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=ru.sbt.ss.event.adapter.StatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_CODE_UNSPECIFIED
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusWithId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusWithId) Reset() {
	*x = StatusWithId{}
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusWithId) ProtoMessage() {}

func (x *StatusWithId) ProtoReflect() protoreflect.Message {
	mi := &file_synes_adapter_v1_EventAdapterService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusWithId.ProtoReflect.Descriptor instead.
func (*StatusWithId) Descriptor() ([]byte, []int) {
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP(), []int{4}
}

func (x *StatusWithId) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusWithId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_synes_adapter_v1_EventAdapterService_proto protoreflect.FileDescriptor

const file_synes_adapter_v1_EventAdapterService_proto_rawDesc = "" +
	"\n" +
	"*synes/adapter/v1/EventAdapterService.proto\x12\x17ru.sbt.ss.event.adapter\x1a\"io/cloudevents/v1/CloudEvent.proto\")\n" +
	"\x0fPublishSettings\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"+\n" +
	"\x11SubscribeSettings\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"y\n" +
	"\rCommitRequest\x12X\n" +
	"\x11subscribeSettings\x18\x01 \x01(\v2*.ru.sbt.ss.event.adapter.SubscribeSettingsR\x11subscribeSettings\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"_\n" +
	"\x06Status\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.ru.sbt.ss.event.adapter.StatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\fStatusWithId\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.ru.sbt.ss.event.adapter.StatusR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*B\n" +
	"\n" +
	"StatusCode\x12\x1b\n" +
	"\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x022\x9a\x02\n" +
	"\x0ePublishService\x12V\n" +
	"\aConnect\x12(.ru.sbt.ss.event.adapter.PublishSettings\x1a\x1f.ru.sbt.ss.event.adapter.Status\"\x00\x12U\n" +
	"\aPublish\x12\x1d.io.cloudevents.v1.CloudEvent\x1a%.ru.sbt.ss.event.adapter.StatusWithId\"\x00(\x010\x01\x12Y\n" +
	"\n" +
	"Disconnect\x12(.ru.sbt.ss.event.adapter.PublishSettings\x1a\x1f.ru.sbt.ss.event.adapter.Status\"\x002\xc3\x01\n" +
	"\x10SubscribeService\x12Z\n" +
	"\tSubscribe\x12*.ru.sbt.ss.event.adapter.SubscribeSettings\x1a\x1d.io.cloudevents.v1.CloudEvent\"\x000\x01\x12S\n" +
	"\x06Commit\x12&.ru.sbt.ss.event.adapter.CommitRequest\x1a\x1f.ru.sbt.ss.event.adapter.Status\"\x00BZ\n" +
	"\x17ru.sbt.ss.event.adapterB\x16EventAdapterServiceApiP\x01Z%api/synes_adapter/v1;synes_adapter_v1b\x06proto3"

var (
	file_synes_adapter_v1_EventAdapterService_proto_rawDescOnce sync.Once
	file_synes_adapter_v1_EventAdapterService_proto_rawDescData []byte
)

func file_synes_adapter_v1_EventAdapterService_proto_rawDescGZIP() []byte {
	file_synes_adapter_v1_EventAdapterService_proto_rawDescOnce.Do(func() {
		file_synes_adapter_v1_EventAdapterService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synes_adapter_v1_EventAdapterService_proto_rawDesc), len(file_synes_adapter_v1_EventAdapterService_proto_rawDesc)))
	})
	return file_synes_adapter_v1_EventAdapterService_proto_rawDescData
}

var file_synes_adapter_v1_EventAdapterService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synes_adapter_v1_EventAdapterService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_synes_adapter_v1_EventAdapterService_proto_goTypes = []any{
	(StatusCode)(0),           // 0: ru.sbt.ss.event.adapter.StatusCode
	(*PublishSettings)(nil),   // 1: ru.sbt.ss.event.adapter.PublishSettings
	(*SubscribeSettings)(nil), // 2: ru.sbt.ss.event.adapter.SubscribeSettings
	(*CommitRequest)(nil),     // 3: ru.sbt.ss.event.adapter.CommitRequest
	(*Status)(nil),            // 4: ru.sbt.ss.event.adapter.Status
	(*StatusWithId)(nil),      // 5: ru.sbt.ss.event.adapter.StatusWithId
	(*v1.CloudEvent)(nil),     // 6: io.cloudevents.v1.CloudEvent
}
var file_synes_adapter_v1_EventAdapterService_proto_depIdxs = []int32{
	2, // 0: ru.sbt.ss.event.adapter.CommitRequest.subscribeSettings:type_name -> ru.sbt.ss.event.adapter.SubscribeSettings
	0, // 1: ru.sbt.ss.event.adapter.Status.status:type_name -> ru.sbt.ss.event.adapter.StatusCode
	4, // 2: ru.sbt.ss.event.adapter.StatusWithId.status:type_name -> ru.sbt.ss.event.adapter.Status
	1, // 3: ru.sbt.ss.event.adapter.PublishService.Connect:input_type -> ru.sbt.ss.event.adapter.PublishSettings
	6, // 4: ru.sbt.ss.event.adapter.PublishService.Publish:input_type -> io.cloudevents.v1.CloudEvent
	1, // 5: ru.sbt.ss.event.adapter.PublishService.Disconnect:input_type -> ru.sbt.ss.event.adapter.PublishSettings
	2, // 6: ru.sbt.ss.event.adapter.SubscribeService.Subscribe:input_type -> ru.sbt.ss.event.adapter.SubscribeSettings
	3, // 7: ru.sbt.ss.event.adapter.SubscribeService.Commit:input_type -> ru.sbt.ss.event.adapter.CommitRequest
	4, // 8: ru.sbt.ss.event.adapter.PublishService.Connect:output_type -> ru.sbt.ss.event.adapter.Status
	5, // 9: ru.sbt.ss.event.adapter.PublishService.Publish:output_type -> ru.sbt.ss.event.adapter.StatusWithId
	4, // 10: ru.sbt.ss.event.adapter.PublishService.Disconnect:output_type -> ru.sbt.ss.event.adapter.Status
	6, // 11: ru.sbt.ss.event.adapter.SubscribeService.Subscribe:output_type -> io.cloudevents.v1.CloudEvent
	4, // 12: ru.sbt.ss.event.adapter.SubscribeService.Commit:output_type -> ru.sbt.ss.event.adapter.Status
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_synes_adapter_v1_EventAdapterService_proto_init() }
func file_synes_adapter_v1_EventAdapterService_proto_init() {
	if File_synes_adapter_v1_EventAdapterService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synes_adapter_v1_EventAdapterService_proto_rawDesc), len(file_synes_adapter_v1_EventAdapterService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_synes_adapter_v1_EventAdapterService_proto_goTypes,
		DependencyIndexes: file_synes_adapter_v1_EventAdapterService_proto_depIdxs,
		EnumInfos:         file_synes_adapter_v1_EventAdapterService_proto_enumTypes,
		MessageInfos:      file_synes_adapter_v1_EventAdapterService_proto_msgTypes,
	}.Build()
	File_synes_adapter_v1_EventAdapterService_proto = out.File
	file_synes_adapter_v1_EventAdapterService_proto_goTypes = nil
	file_synes_adapter_v1_EventAdapterService_proto_depIdxs = nil
}
