// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: synes/adapter/v1/EventAdapterService.proto

package synes_adapter_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "portal.works.prod.sbt/ssd/tools/sc/synd/reactive-stream-adapter-api/grpc/io/cloudevents/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublishService_Connect_FullMethodName    = "/synes.adapter.v1.PublishService/Connect"
	PublishService_Publish_FullMethodName    = "/synes.adapter.v1.PublishService/Publish"
	PublishService_Disconnect_FullMethodName = "/synes.adapter.v1.PublishService/Disconnect"
)

// PublishServiceClient is the client API for PublishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublishServiceClient interface {
	Connect(ctx context.Context, in *PublishSettings, opts ...grpc.CallOption) (*Status, error)
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.CloudEvent, StatusWithId], error)
	Disconnect(ctx context.Context, in *PublishSettings, opts ...grpc.CallOption) (*Status, error)
}

type publishServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublishServiceClient(cc grpc.ClientConnInterface) PublishServiceClient {
	return &publishServiceClient{cc}
}

func (c *publishServiceClient) Connect(ctx context.Context, in *PublishSettings, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PublishService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publishServiceClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.CloudEvent, StatusWithId], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PublishService_ServiceDesc.Streams[0], PublishService_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.CloudEvent, StatusWithId]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PublishService_PublishClient = grpc.BidiStreamingClient[v1.CloudEvent, StatusWithId]

func (c *publishServiceClient) Disconnect(ctx context.Context, in *PublishSettings, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PublishService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishServiceServer is the server API for PublishService service.
// All implementations must embed UnimplementedPublishServiceServer
// for forward compatibility.
type PublishServiceServer interface {
	Connect(context.Context, *PublishSettings) (*Status, error)
	Publish(grpc.BidiStreamingServer[v1.CloudEvent, StatusWithId]) error
	Disconnect(context.Context, *PublishSettings) (*Status, error)
	mustEmbedUnimplementedPublishServiceServer()
}

// UnimplementedPublishServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublishServiceServer struct{}

func (UnimplementedPublishServiceServer) Connect(context.Context, *PublishSettings) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPublishServiceServer) Publish(grpc.BidiStreamingServer[v1.CloudEvent, StatusWithId]) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPublishServiceServer) Disconnect(context.Context, *PublishSettings) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedPublishServiceServer) mustEmbedUnimplementedPublishServiceServer() {}
func (UnimplementedPublishServiceServer) testEmbeddedByValue()                        {}

// UnsafePublishServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublishServiceServer will
// result in compilation errors.
type UnsafePublishServiceServer interface {
	mustEmbedUnimplementedPublishServiceServer()
}

func RegisterPublishServiceServer(s grpc.ServiceRegistrar, srv PublishServiceServer) {
	// If the following call pancis, it indicates UnimplementedPublishServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublishService_ServiceDesc, srv)
}

func _PublishService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublishService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishServiceServer).Connect(ctx, req.(*PublishSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublishService_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublishServiceServer).Publish(&grpc.GenericServerStream[v1.CloudEvent, StatusWithId]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PublishService_PublishServer = grpc.BidiStreamingServer[v1.CloudEvent, StatusWithId]

func _PublishService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublishService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishServiceServer).Disconnect(ctx, req.(*PublishSettings))
	}
	return interceptor(ctx, in, info, handler)
}

// PublishService_ServiceDesc is the grpc.ServiceDesc for PublishService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublishService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synes.adapter.v1.PublishService",
	HandlerType: (*PublishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _PublishService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _PublishService_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _PublishService_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "synes/adapter/v1/EventAdapterService.proto",
}

const (
	SubscribeService_Subscribe_FullMethodName = "/synes.adapter.v1.SubscribeService/Subscribe"
	SubscribeService_Commit_FullMethodName    = "/synes.adapter.v1.SubscribeService/Commit"
)

// SubscribeServiceClient is the client API for SubscribeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscribeServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeSettings, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.CloudEvent], error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Status, error)
}

type subscribeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscribeServiceClient(cc grpc.ClientConnInterface) SubscribeServiceClient {
	return &subscribeServiceClient{cc}
}

func (c *subscribeServiceClient) Subscribe(ctx context.Context, in *SubscribeSettings, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.CloudEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscribeService_ServiceDesc.Streams[0], SubscribeService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeSettings, v1.CloudEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscribeService_SubscribeClient = grpc.ServerStreamingClient[v1.CloudEvent]

func (c *subscribeServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, SubscribeService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscribeServiceServer is the server API for SubscribeService service.
// All implementations must embed UnimplementedSubscribeServiceServer
// for forward compatibility.
type SubscribeServiceServer interface {
	Subscribe(*SubscribeSettings, grpc.ServerStreamingServer[v1.CloudEvent]) error
	Commit(context.Context, *CommitRequest) (*Status, error)
	mustEmbedUnimplementedSubscribeServiceServer()
}

// UnimplementedSubscribeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscribeServiceServer struct{}

func (UnimplementedSubscribeServiceServer) Subscribe(*SubscribeSettings, grpc.ServerStreamingServer[v1.CloudEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSubscribeServiceServer) Commit(context.Context, *CommitRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedSubscribeServiceServer) mustEmbedUnimplementedSubscribeServiceServer() {}
func (UnimplementedSubscribeServiceServer) testEmbeddedByValue()                          {}

// UnsafeSubscribeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscribeServiceServer will
// result in compilation errors.
type UnsafeSubscribeServiceServer interface {
	mustEmbedUnimplementedSubscribeServiceServer()
}

func RegisterSubscribeServiceServer(s grpc.ServiceRegistrar, srv SubscribeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubscribeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscribeService_ServiceDesc, srv)
}

func _SubscribeService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeSettings)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscribeServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeSettings, v1.CloudEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscribeService_SubscribeServer = grpc.ServerStreamingServer[v1.CloudEvent]

func _SubscribeService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscribeService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscribeService_ServiceDesc is the grpc.ServiceDesc for SubscribeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscribeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synes.adapter.v1.SubscribeService",
	HandlerType: (*SubscribeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _SubscribeService_Commit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SubscribeService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "synes/adapter/v1/EventAdapterService.proto",
}
