syntax = "proto3";

import "io/cloudevents/v1/CloudEvent.proto";

option go_package = "api/synes_adapter/v1;synes_adapter_v1";

package synes.adapter.v1;

service PublishService {
    rpc Connect (PublishSettings) returns (Status) {}
    rpc Publish (stream io.cloudevents.v1.CloudEvent) returns (stream StatusWithId) {}
    rpc Disconnect (PublishSettings) returns (Status) {}
}

service SubscribeService {
    rpc Subscribe (SubscribeSettings) returns (stream io.cloudevents.v1.CloudEvent) {
    }
    rpc Commit (CommitRequest) returns (Status) {}
}

message PublishSettings {
    string source = 1;
}

message SubscribeSettings {
    string source = 1;
}

message CommitRequest {
    SubscribeSettings subscribeSettings = 1;
    string id = 2;
}

enum StatusCode {
    STATUS_CODE_UNSPECIFIED = 0;
    FAILED = 1;
    SUCCESS = 2;
}

message Status {
    StatusCode status = 1;
    string message = 2;
}

message StatusWithId {
    Status status = 1;
    string id = 2;
}